theme: jekyll-theme-minimal
title: COS System Maintenance Page
description: College of the Sequoias - System Maintenance Page
github:
  repository_name: "https://www.cos.edu"
  is_project_page: false
  is_user_page: false
