theme: jekyll-theme-minimal
title: System Maintenance Page
logo: /assets/img/logo.png
description: College of the Sequoias - System Maintenance Page
github:
  repository_name: "https://www.cos.edu"
  is_project_page: false
  is_user_page: false
